name: anime_universe
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # cupertino_icons
  cupertino_icons: ^1.0.8
  # dio
  dio: ^5.9.1
  # flutter_bloc
  flutter_bloc: ^9.1.1
  # equatable
  equatable: ^2.0.8
  # get_it
  get_it: ^9.2.1
  # intl
  intl: ^0.20.2
  # go_router
  go_router: ^17.1.0
  # hive_ce
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  # logger
  logger: ^2.6.2
  # cached_network_image
  cached_network_image: ^3.4.1
  # toastification
  toastification: ^3.0.3
  # change_app_package_name
  change_app_package_name: ^1.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  hive_ce_generator: ^1.11.1
  build_runner: ^2.11.1
  flutter_gen: ^5.12.0

flutter:

  uses-material-design: true

  assets:
     - images/
     - icons/
     - fonts/

  fonts:
     - family: SplineSans
       fonts:
         - asset: fonts/SplineSans-Bold.ttf
         - asset: fonts/SplineSans-Light.ttf
         - asset: fonts/SplineSans-Medium.ttf
         - asset: fonts/SplineSans-Regular.ttf
         - asset: fonts/SplineSans-SemiBold.ttf
           style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
