name: anime_universe
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # cupertino_icons
  cupertino_icons: ^1.0.8
  # dio
  dio: ^5.9.1
  # flutter_bloc
  flutter_bloc: ^9.1.1
  # equatable
  equatable: ^2.0.8
  # get_it
  get_it: ^9.2.1
  # intl
  intl: ^0.20.2
  # go_router
  go_router: ^17.1.0
  # hive_ce
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  # logger
  logger: ^2.6.2
  # cached_network_image
  cached_network_image: ^3.4.1
  # toastification
  toastification: ^3.0.3
  # change_app_package_name
  change_app_package_name: ^1.5.0
  # connectivity_plus
  connectivity_plus: ^7.0.0
  # dartz
  dartz: ^0.10.1
  # gap
  gap: ^3.0.1
  #flutter_svg
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  hive_ce_generator: ^1.11.1
  build_runner: ^2.11.1
  flutter_gen: ^5.12.0


flutter_gen:
  output: lib/gen/

  # Optional
  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true

flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/icons/
     - assets/fonts/

  fonts:
     - family: SplineSans
       fonts:
         - asset: assets/fonts/SplineSans/SplineSans-Bold.ttf
         - asset: assets/fonts/SplineSans/SplineSans-Light.ttf
         - asset: assets/fonts/SplineSans/SplineSans-Medium.ttf
         - asset: assets/fonts/SplineSans/SplineSans-Regular.ttf
         - asset: assets/fonts/SplineSans/SplineSans-SemiBold.ttf
           style: italic